name: 'Comment on push'
on:
  push

jobs:
  comment_if_files_changed:
    runs-on: ubuntu-latest
    name: Comment on push with changed files
    steps:
      - name: Hello world action step
        uses: BusseBu/comment-on-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
